[[commands]]
package = "nodejs-18_x"
name = "node"
help = "NodeJS. See https://nodejs.org/en/"

[[commands]]
package = "nixfmt"
name = "nixfmt"
help = "Format nix files"

[[commands]]
package = "custom-rust"
name = "cargo"
help = "Rust package manager, build tool, and more."
